## Where behavior, ripple, parsed replay data lives

In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

### 1. Animal's behavior + annotated future, past, past reward arms
These data live in the table called ```TrialChoice()```.

You will need to have Shijie's table declaration script ```Analysis_SGU.py``` under a folder called ```shijiegu```.

In [3]:
from spyglass.shijiegu.Analysis_SGU import TrialChoice

# helper functions
from spyglass.utils.nwb_helper_fn import get_nwb_copy_filename

[2025-10-27 14:19:27,291][INFO]: DataJoint 0.14.4 connected to shijiegu-alt@lmf-db.cin.ucsf.edu:3306

Our datasets are organized in units of 
- the name of the rat
- the day on which recording happened.

The 5 rats I have are Molly, Eliot, Julio, Klein, and Lewis. The dates are listed below:
- Molly: 20220415,20220416,20220417,20220418,20220419,20220420
- Eliot: 20221018,20221019,20221020,20221021,20221022,20221023,20221024,20221025,20221026
- Julio: 20230731,20230801,20230802,20230803,20230804,20230805,20230806,20230807,20230808,20230809,20230810,20230811
- Klein: 20231101,20231102,20231103,20231104,20231105,20231106,20231107,20231108,20231109,20231111
- Lewis: 20240105, 20240106, 20240107,20240108,20240109,20240110,20240113,20240114

In [4]:
'''choose a day'''
nwb_file_name = 'molly20220418.nwb' # animal name + data + .nwb

# some idiosynchrocy about Frank Lab database.
# The idea is that large raw ephys lives in nwb_file_name and the rest lives in "nwb_copy_file_name"
# So to get any processed data, use nwb_copy_file_name, which just adds an underscore after the date.
nwb_copy_file_name = get_nwb_copy_filename(nwb_file_name)  #'molly20220418_.nwb'

# all the maze sessions/epochs on this day
all_epochs=list((TrialChoice() & 
                 {'nwb_file_name':nwb_copy_file_name}).fetch('epoch'))
print('epochs all this day:',all_epochs)

epochs all this day: [2, 4, 6, 8, 10]

In [5]:
pd.set_option('display.max_rows', None)

In [6]:
'''choose an epoch'''
epoch_num = 4

In [7]:
'''get the behavior on this day and this epoch'''
T=pd.DataFrame((TrialChoice() & {'nwb_file_name':nwb_copy_file_name,
                                 'epoch':epoch_num}).fetch1('choice_reward'))
T

,timestamp_H,Home,timestamp_O,OuterWellIndex,rewardNum,current,future_H,future_O,past,past_reward
1,1.650308e+09,1.0,1.650308e+09,4.0,1.0,4.0,4.0,2.0,NaN,NaN
2,1.650308e+09,1.0,1.650308e+09,2.0,1.0,2.0,2.0,3.0,4.0,NaN
3,1.650308e+09,1.0,1.650308e+09,3.0,2.0,3.0,3.0,1.0,2.0,NaN
4,1.650308e+09,1.0,1.650308e+09,1.0,1.0,1.0,1.0,4.0,3.0,3.0
5,1.650308e+09,1.0,1.650308e+09,4.0,2.0,4.0,4.0,2.0,1.0,3.0
6,1.650308e+09,1.0,1.650308e+09,2.0,2.0,2.0,2.0,3.0,4.0,4.0
7,1.650308e+09,1.0,1.650308e+09,3.0,1.0,3.0,3.0,1.0,2.0,2.0
8,1.650308e+09,1.0,1.650308e+09,1.0,2.0,1.0,1.0,4.0,3.0,2.0
9,1.650308e+09,1.0,1.650308e+09,4.0,1.0,4.0,4.0,2.0,1.0,1.0
10,1.650308e+09,1.0,1.650308e+09,2.0,1.0,2.0,2.0,1.0,4.0,1.0
11,1.650308e+09,1.0,1.650308e+09,1.0,1.0,1.0,1.0,3.0,2.0,1.0
12,1.650308e+09,1.0,1.650308e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
13,1.650308e+09,1.0,1.650308e+09,4.0,2.0,4.0,4.0,1.0,3.0,3.0
14,1.650308e+09,1.0,1.650308e+09,1.0,1.0,1.0,1.0,2.0,4.0,4.0
15,1.650308e+09,1.0,1.650308e+09,2.0,2.0,2.0,2.0,4.0,1.0,4.0
16,1.650308e+09,1.0,1.650308e+09,4.0,1.0,4.0,4.0,3.0,2.0,2.0
17,1.650308e+09,1.0,1.650308e+09,3.0,1.0,3.0,3.0,1.0,4.0,2.0
18,1.650308e+09,1.0,1.650308e+09,1.0,2.0,1.0,1.0,4.0,3.0,2.0
19,1.650308e+09,1.0,1.650308e+09,4.0,1.0,4.0,4.0,2.0,1.0,1.0
20,1.650308e+09,1.0,1.650308e+09,2.0,1.0,2.0,2.0,3.0,4.0,1.0
21,1.650308e+09,1.0,1.650308e+09,3.0,2.0,3.0,3.0,1.0,2.0,1.0
22,1.650308e+09,1.0,1.650308e+09,1.0,1.0,1.0,1.0,4.0,3.0,3.0
23,1.650308e+09,1.0,1.650308e+09,4.0,2.0,4.0,4.0,2.0,1.0,3.0
24,1.650308e+09,1.0,1.650308e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
25,1.650308e+09,1.0,1.650308e+09,1.0,2.0,1.0,1.0,3.0,2.0,2.0
26,1.650308e+09,1.0,1.650308e+09,3.0,2.0,3.0,3.0,1.0,1.0,1.0
27,1.650308e+09,1.0,1.650308e+09,1.0,1.0,1.0,1.0,1.0,3.0,3.0
28,1.650308e+09,1.0,1.650308e+09,1.0,1.0,1.0,1.0,4.0,1.0,3.0
29,1.650308e+09,1.0,1.650308e+09,4.0,2.0,4.0,4.0,2.0,1.0,3.0
30,1.650308e+09,1.0,1.650308e+09,2.0,2.0,2.0,2.0,3.0,4.0,4.0
31,1.650308e+09,1.0,1.650308e+09,3.0,1.0,3.0,3.0,4.0,2.0,2.0
32,1.650308e+09,1.0,1.650308e+09,4.0,1.0,4.0,4.0,1.0,3.0,2.0
33,1.650308e+09,1.0,1.650308e+09,1.0,2.0,1.0,1.0,2.0,4.0,2.0
34,1.650308e+09,1.0,1.650308e+09,2.0,1.0,2.0,2.0,4.0,1.0,1.0
35,1.650308e+09,1.0,1.650308e+09,4.0,1.0,4.0,4.0,1.0,2.0,1.0
36,1.650308e+09,1.0,1.650308e+09,1.0,1.0,1.0,1.0,3.0,4.0,1.0
37,1.650308e+09,1.0,1.650309e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
38,1.650309e+09,1.0,1.650309e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
39,1.650309e+09,1.0,1.650309e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
40,1.650309e+09,1.0,1.650309e+09,1.0,2.0,1.0,1.0,4.0,2.0,2.0
41,1.650309e+09,1.0,1.650309e+09,4.0,1.0,4.0,4.0,3.0,1.0,1.0
42,1.650309e+09,1.0,1.650309e+09,3.0,2.0,3.0,3.0,2.0,4.0,1.0
43,1.650309e+09,1.0,1.650309e+09,2.0,1.0,2.0,2.0,4.0,3.0,3.0
44,1.650309e+09,1.0,1.650309e+09,4.0,2.0,4.0,4.0,1.0,2.0,3.0
45,1.650309e+09,1.0,1.650309e+09,1.0,1.0,1.0,1.0,3.0,4.0,4.0
46,1.650309e+09,1.0,1.650309e+09,3.0,1.0,3.0,3.0,2.0,1.0,4.0
47,1.650309e+09,1.0,1.650309e+09,2.0,2.0,2.0,2.0,4.0,3.0,4.0
48,1.650309e+09,1.0,1.650309e+09,4.0,1.0,4.0,4.0,1.0,2.0,2.0
49,NaN,NaN,1.650309e+09,1.0,0.0,1.0,1.0,3.0,4.0,2.0
50,1.650309e+09,1.0,1.650309e+09,3.0,1.0,3.0,3.0,1.0,1.0,2.0
51,1.650309e+09,1.0,1.650309e+09,1.0,2.0,1.0,1.0,4.0,3.0,2.0
52,1.650309e+09,1.0,1.650309e+09,4.0,1.0,4.0,4.0,2.0,1.0,1.0
53,1.650309e+09,1.0,1.650309e+09,2.0,1.0,2.0,2.0,3.0,4.0,1.0
54,1.650309e+09,1.0,1.650309e+09,3.0,2.0,3.0,3.0,4.0,2.0,1.0
55,1.650309e+09,1.0,1.650309e+09,4.0,2.0,4.0,4.0,1.0,3.0,3.0
56,1.650309e+09,1.0,1.650309e+09,1.0,1.0,1.0,1.0,4.0,4.0,4.0
57,1.650309e+09,1.0,1.650309e+09,4.0,1.0,4.0,4.0,2.0,1.0,4.0
58,1.650309e+09,1.0,1.650309e+09,2.0,2.0,2.0,2.0,4.0,4.0,4.0
59,1.650309e+09,1.0,1.650309e+09,4.0,1.0,4.0,4.0,3.0,2.0,2.0
60,1.650309e+09,1.0,1.650309e+09,3.0,1.0,3.0,3.0,1.0,4.0,2.0
61,1.650309e+09,1.0,1.650309e+09,1.0,2.0,1.0,1.0,4.0,3.0,2.0
62,1.650309e+09,1.0,1.650309e+09,4.0,1.0,4.0,4.0,2.0,1.0,1.0
63,1.650309e+09,1.0,1.650309e+09,2.0,1.0,2.0,2.0,3.0,4.0,1.0
64,1.650309e+09,1.0,1.650309e+09,3.0,2.0,3.0,3.0,4.0,2.0,1.0
65,1.650309e+09,1.0,1.650309e+09,4.0,2.0,4.0,4.0,1.0,3.0,3.0
66,1.650309e+09,1.0,1.650309e+09,1.0,1.0,1.0,1.0,2.0,4.0,4.0
67,1.650309e+09,1.0,1.650309e+09,2.0,2.0,2.0,2.0,4.0,1.0,4.0
68,1.650309e+09,1.0,1.650309e+09,4.0,1.0,4.0,4.0,1.0,2.0,2.0
69,1.650309e+09,1.0,1.650309e+09,1.0,2.0,1.0,1.0,3.0,4.0,2.0
70,1.650309e+09,1.0,1.650309e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
71,1.650309e+09,1.0,1.650309e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
72,1.650309e+09,1.0,1.650309e+09,2.0,2.0,2.0,2.0,4.0,4.0,4.0
73,1.650309e+09,1.0,1.650309e+09,4.0,1.0,4.0,4.0,1.0,2.0,2.0
74,1.650309e+09,1.0,1.650309e+09,1.0,2.0,1.0,1.0,3.0,4.0,2.0
75,1.650309e+09,1.0,1.650310e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
76,1.650310e+09,1.0,1.650310e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
77,1.650310e+09,1.0,1.650310e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
78,1.650310e+09,1.0,1.650310e+09,1.0,2.0,1.0,1.0,4.0,2.0,2.0
79,1.650310e+09,1.0,1.650310e+09,4.0,1.0,4.0,4.0,3.0,1.0,1.0
80,1.650310e+09,1.0,1.650310e+09,3.0,2.0,3.0,3.0,2.0,4.0,1.0
81,1.650310e+09,1.0,1.650310e+09,2.0,2.0,2.0,2.0,NaN,3.0,3.0
82,1.650310e+09,1.0,NaN,NaN,0.0,NaN,NaN,NaN,2.0,NaN

#### Notes:
**timestamp_H**: Unix time for poking the home well.
Home: if the animal poked the home well at that trial. Animal is pretrained to do that to initiate a trial. Feel free to ignore the few trials that the animal skipped the home. I call these trials "illegal trials".

**timestamp_O**: Unix time for poking the outer well.

**OuterWellIndex**: The outer well/arm choice animal makes.

**rewardNum**: 0 - illegal trial; 1 - incorrect trial; 2 - correct trial

The rest can be derived from previous columns.

**current**: the same as OuterWellIndex, can ignore.

**future_H**: the same as OuterWellIndex, can ignore.

**future_O**: the arm the rat will choose on the next trial.

**past**: the arm the rat picked on the last trial.

**past_reward**: the arm the rat picked on the last trial, and in addition, he got a reward there.

### Work in progress from below.

### 2. Animal position data.
You might need this or might not.

In [8]:
from spyglass.common.common_position import IntervalPositionInfo, RawPosition, IntervalLinearizedPosition, TrackGraph

### 3. Spiking data

### 4. Replay data
Coming soon, I need to push the dataframes into the database in a new format for all rats. But it will look like this:

In [9]:
from spyglass.shijiegu.load import load_run_sessions
from spyglass.shijiegu.Analysis_SGU import RippleTimesWithDecode

In [10]:
# Find all sessions on this day
run_session_ids, run_session_names, pos_session_names = load_run_sessions(nwb_copy_file_name)

*nwb_file_name *epoch    epoch_name     position_inter
+------------+ +-------+ +------------+ +------------+
molly20220418_ 1         01_Seq2Sleep1  pos 0 valid ti
molly20220418_ 2         02_Seq2Session pos 1 valid ti
molly20220418_ 3         03_Seq2Sleep2  pos 2 valid ti
molly20220418_ 4         04_Seq2Session pos 3 valid ti
molly20220418_ 5         05_Seq2Sleep3  pos 4 valid ti
molly20220418_ 6         06_Seq2Session pos 5 valid ti
molly20220418_ 7         07_Seq2Sleep4  pos 6 valid ti
molly20220418_ 8         08_Seq2Session pos 7 valid ti
molly20220418_ 9         09_Seq2Sleep5  pos 8 valid ti
molly20220418_ 10        10_Seq2Session pos 9 valid ti
molly20220418_ 11        11_Seq2Sleep6  pos 10 valid t
 (Total: 11)

In [11]:
# pick a session
session_name = run_session_names[0]
print(session_name)

02_Seq2Session1

In [12]:
query = {'nwb_file_name': nwb_copy_file_name,
         'interval_list_name': session_name,
         "classifier_param_name":"default_decoding_gpu_4armMaze",
         "encoding_set":"2Dheadspeed_above_4",
         "decode_threshold_method":"MUA_M05SD"}
path_to_ripple_times = (RippleTimesWithDecode & query).fetch1("ripple_times")

try: # old format for data processed later
    ripple_times = pd.DataFrame(path_to_ripple_times)
except: # new format for data processed later
    ripple_times = pd.read_pickle(path_to_ripple_times)

### for each ripple event, I have parsed
- the trial in which it occured
- the start time, end time of each ripple
- the continuous interval(s) within the ripple
- the fragmented interval(s) within the ripple
- and other statistics about that ripple

In [13]:
ripple_times

,event_number,start_time,animal_location,trial_number,cont_intvl,frag_intvl,cont_intvl_replay,end_time,duration,mean_zscore,median_zscore,max_zscore,min_zscore,speed_at_start,speed_at_end,max_speed,min_speed,median_speed,mean_speed
0,1,1.650303e+09,well4,1,"[[1650303252.936586, 1650303253.006586]]",[],[[]],1.650303e+09,0.071000,147.215883,158.129299,218.404138,82.185485,1.719982e+00,3.405536e+00,3.405536e+00,1.719982e+00,2.587314e+00,2.577609e+00
1,2,1.650303e+09,well4,1,"[[1650303254.1365852, 1650303254.298585]]",[],[[4]],1.650303e+09,0.165000,126.656481,122.053295,183.785176,85.441928,3.995007e+00,3.992519e+00,3.995007e+00,1.258586e+00,2.547996e+00,2.482513e+00
2,3,1.650303e+09,well2,1,"[[1650303261.1885786, 1650303261.2765784]]",[],[[2]],1.650303e+09,0.089000,142.311060,135.305319,211.987384,84.171689,3.982026e+00,1.598308e+00,3.982026e+00,1.598308e+00,2.539862e+00,2.625220e+00
3,4,1.650303e+09,well2,1,"[[1650303261.706578, 1650303261.742578]]",[],[[2]],1.650303e+09,0.037000,150.140898,159.832319,201.986928,82.264354,2.962627e+00,3.081341e+00,3.081341e+00,2.962627e+00,3.052335e+00,3.048279e+00
4,5,1.650303e+09,arm2,1,"[[1650303272.372568, 1650303272.538568]]",[],[[2]],1.650303e+09,0.169000,166.984238,146.755207,312.191901,88.889942,3.978831e+00,3.995354e+00,3.995354e+00,1.937071e+00,2.583384e+00,2.689648e+00
5,6,1.650303e+09,home,3,"[[1650303280.1345608, 1650303280.2345607]]",[],[[0]],1.650303e+09,0.101000,153.282340,118.802612,316.836065,82.249822,3.973340e+00,1.257277e+00,3.973340e+00,1.257277e+00,2.570525e+00,2.582997e+00
6,7,1.650303e+09,well3,3,"[[1650303293.4465485, 1650303293.4965484]]","[[1650303293.4145484, 1650303293.4445484]]",[[3]],1.650303e+09,0.105000,128.103350,123.202559,204.418017,81.382671,1.235064e+00,2.444325e-01,1.235064e+00,2.444325e-01,6.385950e-01,6.747193e-01
7,8,1.650303e+09,well3,3,"[[1650303293.7365482, 1650303293.8225482]]",[],[[3]],1.650303e+09,0.088000,129.819578,114.717974,239.043078,81.267749,5.162954e-01,3.630146e-01,5.162954e-01,3.585136e-01,3.777372e-01,4.068452e-01
8,9,1.650303e+09,well3,3,"[[1650303294.2185478, 1650303294.2805476]]",[],[[3]],1.650303e+09,0.065000,137.941324,148.005203,224.976581,82.124282,2.137516e+00,2.138567e+00,2.205644e+00,2.137516e+00,2.171794e+00,2.171811e+00
9,10,1.650303e+09,well3,3,"[[1650303294.6605473, 1650303294.7425473]]",[],[[3]],1.650303e+09,0.083000,131.804506,115.990104,240.983384,81.561554,1.195341e+00,1.324755e+00,1.324755e+00,9.653943e-01,1.083308e+00,1.101802e+00
10,11,1.650303e+09,well3,3,"[[1650303296.4985456, 1650303296.5785456]]",[],[[]],1.650303e+09,0.081000,155.216588,127.647402,261.883430,84.269876,1.412973e+00,8.865429e-01,1.624992e+00,8.865429e-01,1.468588e+00,1.405673e+00
11,12,1.650303e+09,well3,3,"[[1650303297.8385444, 1650303298.006544]]",[],[[3]],1.650303e+09,0.179001,149.582695,138.883395,285.113044,81.249362,6.289147e-01,1.631531e+00,1.631531e+00,4.918890e-01,1.238229e+00,1.155453e+00
12,13,1.650303e+09,well3,3,"[[1650303300.9905417, 1650303301.1425414]]",[],[[3]],1.650303e+09,0.154000,184.711261,187.512399,302.259240,107.303210,3.988061e+00,3.986414e+00,3.988061e+00,4.310878e-01,1.678416e+00,1.832960e+00
13,14,1.650303e+09,well1,3,"[[1650303310.9445322, 1650303311.0265322]]",[],[[1]],1.650303e+09,0.084000,129.541541,111.547245,223.086421,81.307234,1.058523e+00,7.319403e-01,1.058523e+00,7.319403e-01,8.322279e-01,8.570337e-01
14,15,1.650303e+09,well2,6,"[[1650303357.280489, 1650303357.4604888]]",[],[[2]],1.650303e+09,0.181000,127.723414,119.379516,209.613838,83.236997,3.996288e+00,2.060439e+00,3.996288e+00,2.060439e+00,2.522307e+00,2.658984e+00
15,16,1.650303e+09,well2,6,"[[1650303364.4344823, 1650303364.5224822]]",[],[[2]],1.650303e+09,0.090000,176.710356,124.771077,448.045443,81.733295,7.549432e-01,9.130558e-01,9.130558e-01,4.375384e-01,4.768822e-01,5.527865e-01
16,17,1.650303e+09,home,7,"[[1650303373.130474, 1650303373.156474], [1650...",[],"[[4], []]",1.650303e+09,0.087000,142.339276,136.999627,210.393112,83.317335,2.211082e-01,3.250299e-01,3.250299e-01,2.211082e-01,2.544069e-01,2.623787e-01
17,18,1.650303e+09,home,7,"[[1650303375.256472, 1650303375.3084722]]",[],[[0]],1.650303e+09,0.053000,127.698690,123.893069,175.548174,81.330489,1.144955e-01,1.885497e-01,1.903841e-01,1.057995e-01,1.464653e-01,1.471969e-01
18,19,1.650303e+09,well3,7,"[[1650303383.9384642, 1650303383.990464]]",[],[[3]],1.650303e+09,0.053000,149.364474,150.917563,225.870752,81.419289,3.061959e+00,1.515264e+00,3.061959e+00,1.515264e+00,2.226348e+00,2.243292e+00
19,20,1.650303e+09,well3,7,"[[1650303386.7924614, 1650303386.908461]]",[],[[3]],1.650303e+09,0.119000,139.245898,117.355353,226.725401,81.718644,3.990800e+00,3.112600e+00,3.990800e+00,2.310233e+00,2.586885e+00,2.735957e+00
20,21,1.650303e+09,well3,7,"[[1650303386.918461, 1650303386.9584613]]",[],[[]],1.650303e+09,0.042000,170.424746,152.313493,278.379931,83.006303,3.276156e+00,3.990588e+00,3.990588e+00,3.276156e+00,3.656219e+00,3.653007e+00
21,22,1.650303e+09,well3,7,"[[1650303386.9744613, 1650303387.0124612]]",[],[[]],1.650303e+09,0.039000,200.770646,199.049209,259.180061,134.925328,3.998353e+00,3.988432e+00,3.998353e+00,3.853880e+00,3.926116e+00,3.926398e+00
22,23,1.650303e+09,home,8,"[[1650303400.7564485, 1650303400.7924483], [16...",[],"[[], []]",1.650303e+09,0.071000,123.141019,119.288274,168.359803,81.482730,2.936632e-01,1.105411e-01,2.936632e-01,1.105411e-01,1.563745e-01,1.738231e-01
23,24,1.650303e+09,home,8,"[[1650303401.8344474, 1650303401.8804474], [16...","[[1650303401.8824475, 1650303401.9264474]]","[[0], [4]]",1.650303e+09,0.151000,134.149987,135.646059,219.911563,81.004740,2.166473e-01,6.540627e-02,2.166473e-01,2.443645e-02,1.425802e-01,1.310175e-01
24,25,1.650303e+09,well1,8,"[[1650303413.3424368, 1650303413.3824368], [16...",[],"[[], [4]]",1.650303e+09,0.230001,125.445182,118.905882,228.278962,81.585000,4.865919e-01,8.567840e-02,4.865919e-01,8.500159e-02,3.833588e-01,3.377849e-01
25,26,1.650303e+09,home,9,"[[1650303424.770426, 1650303424.836426], [1650...","[[1650303424.9904258, 1650303425.0244255]]","[[2], [2]]",1.650303e+09,0.277001,151.877536,142.690978,264.612615,81.394957,2.912693e-01,2.659710e-01,4.508893e-01,2.421213e-01,3.553053e-01,3.502110e-01
26,27,1.650303e+09,home,10,"[[1650303442.3204098, 1650303442.3664095]]",[],[[0]],1.650303e+09,0.047000,135.771424,131.105461,194.904621,81.269611,6.636436e-01,4.554915e-01,6.636436e-01,4.554915e-01,5.634587e-01,5.612890e-01
27,28,1.650303e+09,home,10,"[[1650303442.8784091, 1650303442.9244092], [16...","[[1650303442.926409, 1650303443.012409], [1650...","[[], [], [1]]",1.650303e+09,0.400001,159.726131,114.451144,591.174084,81.592641,2.416010e-01,4.320247e-01,4.417959e-01,5.600379e-02,2.272183e-01,2.297004e-01
28,29,1.650303e+09,well2,10,"[[1650303449.7024028, 1650303449.9024026]]",[],[[2]],1.650303e+09,0.201000,126.670891,122.645441,191.397830,82.895791,3.978424e+00,1.888776e+00,3.978424e+00,1.888776e+00,2.101935e+00,2.349449e+00
29,30,1.650303e+09,well2,10,"[[1650303452.3124003, 1650303452.3944004]]",[],[[]],1.650303e+09,0.083000,193.106560,173.871946,355.907942,109.379195,3.992846e+00,3.977283e+00,3.992846e+00,2.368429e+00,3.158578e+00,3.163197e+00
30,31,1.650303e+09,well2,10,"[[1650303453.1743996, 1650303453.2263994]]",[],[[2]],1.650303e+09,0.055000,153.448808,159.779965,224.190338,82.298322,3.990348e+00,2.442695e+00,3.990348e+00,2.442695e+00,3.095281e+00,3.156656e+00
31,32,1.650303e+09,center1,12,"[[1650303499.3903563, 1650303499.754356]]",[],[[]],1.650303e+09,0.366001,156.357499,142.998055,292.673507,82.700662,3.988285e+00,3.005020e+00,3.988285e+00,3.964153e-01,1.699106e+00,1.782766e+00
32,33,1.650304e+09,center1,12,"[[1650303500.5803554, 1650303500.6183553]]",[],[[]],1.650304e+09,0.039000,154.159288,173.540820,202.103396,81.727598,1.849080e+00,2.669026e+00,2.669026e+00,1.849080e+00,2.194259e+00,2.228798e+00
33,34,1.650304e+09,center1,12,"[[1650303500.6263554, 1650303500.6843553]]",[],[[]],1.650304e+09,0.061000,143.471533,131.170196,245.632122,80.998617,2.812531e+00,3.718701e+00,3.718701e+00,2.812531e+00,3.408021e+00,3.358226e+00
34,35,1.650304e+09,center1,12,"[[1650303501.808354, 1650303501.888354]]",[],[[]],1.650304e+09,0.095000,136.012020,111.690545,277.039752,84.769552,2.165043e+00,3.895244e+00,3.895244e+00,2.165043e+00,2.841053e+00,2.895423e+00
35,36,1.650304e+09,center1,12,"[[1650303502.3423538, 1650303502.5363536]]",[],[[3]],1.650304e+09,0.197001,133.852073,118.642085,236.883901,82.884151,1.556501e+00,3.794486e+00,3.794486e+00,1.556501e+00,2.621792e+00,2.644817e+00
36,37,1.650304e+09,center1,12,"[[1650303504.6763515, 1650303504.7403514]]",[],[[]],1.650304e+09,0.096000,162.567495,142.323730,292.838099,82.401776,2.163684e+00,2.694656e+00,2.694656e+00,2.163684e+00,2.339399e+00,2.371714e+00
37,38,1.650304e+09,arm4,12,"[[1650303506.5683498, 1650303506.6443498]]",[],[[]],1.650304e+09,0.078000,141.108050,105.747273,300.892714,82.644832,3.579108e+00,3.883831e+00,3.964360e+00,3.579108e+00,3.878416e+00,3.837963e+00
38,39,1.650304e+09,center1,12,"[[1650303508.470348, 1650303508.546348]]",[],[[]],1.650304e+09,0.077000,147.916095,147.701510,229.312353,85.340792,2.427884e+00,3.986336e+00,3.986336e+00,2.427884e+00,2.977979e+00,3.064985e+00
39,40,1.650304e+09,center1,12,"[[1650303508.8823476, 1650303508.9503477], [16...",[],"[[], []]",1.650304e+09,0.121000,183.525041,174.163634,354.676806,83.045261,3.995155e+00,6.276111e-01,3.995155e+00,6.276111e-01,1.665654e+00,1.863145e+00
40,41,1.650304e+09,center1,12,[],"[[1650303509.1623473, 1650303509.1963472]]",[],1.650304e+09,0.049000,136.393283,117.494584,222.929520,82.122286,1.189887e+00,1.824266e+00,1.824266e+00,1.189887e+00,1.508289e+00,1.509404e+00
41,42,1.650304e+09,center1,12,"[[1650303509.540347, 1650303509.612347]]",[],[[]],1.650304e+09,0.074000,133.528015,134.738556,180.609614,81.381517,1.365493e+00,2.677576e+00,2.677576e+00,1.365493e+00,1.855692e+00,1.918576e+00
42,43,1.650304e+09,center1,12,"[[1650303509.654347, 1650303509.694347], [1650...",[],"[[], []]",1.650304e+09,0.081000,121.743130,98.912357,209.165601,81.315845,3.400967e+00,3.593713e+00,3.750477e+00,3.400967e+00,3.640226e+00,3.623988e+00
43,44,1.650304e+09,center1,12,"[[1650303509.7723467, 1650303509.8463466]]",[],[[]],1.650304e+09,0.091000,144.670371,122.341799,269.436959,81.521016,3.302752e+00,1.915195e+00,3.302752e+00,1.915195e+00,2.513743e+00,2.537899e+00
44,45,1.650304e+09,center1,12,"[[1650303509.8563466, 1650303509.9063466]]",[],[[]],1.650304e+09,0.052000,139.264701,132.675075,202.728572,81.466950,1.866613e+00,1.961475e+00,1.961475e+00,1.774373e+00,1.848229e+00,1.855661e+00
45,46,1.650304e+09,center1,12,"[[1650303513.4763434, 1650303513.5163434], [16...",[],"[[], []]",1.650304e+09,0.131000,141.832404,142.748249,208.674914,94.934814,3.961905e+00,3.987030e+00,3.987030e+00,1.652959e+00,2.575662e+00,2.724131e+00
46,47,1.650304e+09,center1,12,"[[1650303514.2083426, 1650303514.3503425]]",[],[[4]],1.650304e+09,0.145000,132.456445,113.602772,232.520338,84.471968,3.961916e+00,3.982838e+00,3.982838e+00,2.518732e+00,3.054903e+00,3.147568e+00
47,48,1.650304e+09,center1,12,"[[1650303514.800342, 1650303514.888342]]",[],[[4]],1.650304e+09,0.090000,140.438634,129.605871,267.513914,81.154166,1.906666e+00,2.116934e+00,2.116934e+00,1.734500e+00,1.870570e+00,1.890086e+00
48,49,1.650304e+09,center1,12,"[[1650303515.914341, 1650303515.960341]]",[],[[]],1.650304e+09,0.048000,264.306079,278.347170,381.182919,82.214345,3.151175e+00,3.998027e+00,3.998027e+00,3.151175e+00,3.604866e+00,3.589504e+00
49,50,1.650304e+09,center1,12,"[[1650303516.2163408, 1650303516.2683408]]",[],[[]],1.650304e+09,0.053000,141.457994,114.144155,247.637031,83.538213,3.991583e+00,3.303293e+00,3.991583e+00,3.303293e+00,3.683781e+00,3.674334e+00
50,51,1.650304e+09,center1,12,"[[1650303516.3983407, 1650303516.5003405]]",[],[[4]],1.650304e+09,0.105000,155.894556,150.226424,293.629093,81.577740,9.038017e-01,1.333238e+00,1.333238e+00,8.273567e-01,1.050368e+00,1.071619e+00
51,52,1.650304e+09,center1,12,"[[1650303516.6783404, 1650303516.7523403]]",[],[[]],1.650304e+09,0.076000,150.006074,149.124430,206.907796,81.000846,3.394381e-01,1.668190e+00,1.668190e+00,3.394381e-01,9.662366e-01,9.771483e-01
52,53,1.650304e+09,arm0,12,"[[1650303520.370337, 1650303520.414337], [1650...","[[1650303520.4163368, 1650303520.450337]]","[[], [0]]",1.650304e+09,0.110000,160.869362,160.720879,224.167260,116.806699,3.976755e+00,3.968250e+00,3.976755e+00,2.329259e+00,3.027937e+00,3.071676e+00
53,54,1.650304e+09,well2,13,"[[1650303561.5002985, 1650303561.6122985]]",[],[[2]],1.650304e+09,0.114000,164.202536,156.261705,229.200192,99.818061,3.982179e+00,3.993281e+00,3.993281e+00,5.252417e-01,2.240698e+00,2.262998e+00
54,55,1.650304e+09,well2,13,"[[1650303562.4342978, 1650303562.4882977]]",[],[[2]],1.650304e+09,0.056000,170.684785,135.863588,297.442903,109.600741,3.998934e+00,3.956714e+00,3.998934e+00,2.910154e+00,3.380104e+00,3.399289e+00
55,56,1.650304e+09,home,15,"[[1650303583.7942777, 1650303583.8322778], [16...",[],"[[2], [], [2], [3]]",1.650304e+09,0.309001,180.479750,154.259954,412.374683,82.946255,5.787516e-01,1.981015e-01,1.149264e+00,1.981015e-01,8.349719e-01,7.722045e-01
56,57,1.650304e+09,well1,15,"[[1650303595.1262672, 1650303595.256267]]","[[1650303595.078267, 1650303595.124267]]",[[]],1.650304e+09,0.195000,115.255733,100.136611,253.323493,81.987141,2.133438e+00,2.547427e+00,3.053922e+00,2.133438e+00,2.830889e+00,2.761350e+00
57,58,1.650304e+09,well1,15,"[[1650303595.282267, 1650303595.326267], [1650...",[],"[[1], []]",1.650304e+09,0.146000,109.946077,99.833250,168.394889,81.019675,2.241895e+00,3.898718e-01,2.241895e+00,3.898718e-01,1.228782e+00,1.257012e+00
58,59,1.650304e+09,well1,15,"[[1650303597.1842654, 1650303597.418265]]",[],[[1]],1.650304e+09,0.236001,119.506405,108.369580,218.806188,81.549050,4.526450e-01,1.388953e+00,1.388953e+00,4.526450e-01,1.002775e+00,9.859982e-01
59,60,1.650304e+09,home,16,[],"[[1650303605.7762573, 1650303605.8382573]]",[],1.650304e+09,0.071000,152.517440,134.663091,233.113843,81.364661,3.768930e-01,1.148155e-01,3.768930e-01,1.148155e-01,2.595521e-01,2.563004e-01
60,61,1.650304e+09,home,16,"[[1650303606.052257, 1650303606.076257], [1650...","[[1650303606.078257, 1650303606.156257]]","[[], [0], []]",1.650304e+09,0.198000,206.968426,159.260912,442.872322,81.361724,6.316906e-01,3.966296e-01,6.316906e-01,1.363984e-01,3.180930e-01,3.402855e-01
61,62,1.650304e+09,well3,16,"[[1650303619.826244, 1650303619.872244]]",[],[[3]],1.650304e+09,0.048000,145.108976,135.396508,223.612502,82.217926,1.253440e+00,1.382234e+00,1.382234e+00,1.253440e+00,1.319123e+00,1.318699e+00
62,63,1.650304e+09,center1,17,"[[1650303641.8042238, 1650303641.8682237], [16...","[[1650303641.8702235, 1650303641.8922236]]","[[2], [2]]",1.650304e+09,0.148000,192.533923,167.880449,380.832807,81.815509,2.093679e-01,8.385178e-01,8.385178e-01,1.140320e-01,2.318375e-01,3.440410e-01
63,64,1.650304e+09,center1,17,"[[1650303642.346223, 1650303642.416223]]","[[1650303642.4182231, 1650303642.4642231]]",[[2]],1.650304e+09,0.131000,192.269048,169.512978,301.593341,81.303974,3.168956e-01,2.566331e-01,3.168956e-01,7.460716e-02,1.741133e-01,1.804504e-01
64,65,1.650304e+09,center1,17,"[[1650303644.0102215, 1650303644.0502217], [16...",[],"[[4], []]",1.650304e+09,0.075000,126.091902,112.160892,193.490003,81.531989,3.209593e-01,4.217278e-01,4.217278e-01,3.209593e-01,4.114357e-01,3.924727e-01
65,66,1.650304e+09,center1,17,"[[1650303644.4402213, 1650303644.5142212], [16...","[[1650303644.5162213, 1650303644.6002212]]","[[], [1]]",1.650304e+09,0.207000,151.109283,144.342359,249.723687,81.322884,9.888630e-01,1.033600e+00,1.033600e+00,3.307337e-01,6.118876e-01,6.270707e-01
66,67,1.650304e+09,center1,17,"[[1650303645.1482203, 1650303645.2802205]]",[],[[]],1.650304e+09,0.135000,122.833720,105.588517,205.841762,81.490502,7.656376e-01,1.405203e-01,7.731352e-01,1.405203e-01,4.830073e-01,4.712534e-01
67,68,1.650304e+09,center1,17,"[[1650303645.6502202, 1650303645.84822]]",[],[[3]],1.650304e+09,0.201000,123.397703,118.832079,201.121170,82.046091,3.918129e-01,2.007246e-01,3.918129e-01,8.088219e-02,1.479412e-01,1.663451e-01
68,69,1.650304e+09,center1,17,"[[1650303646.0462198, 1650303646.1082196]]",[],[[]],1.650304e+09,0.065000,142.743219,148.178880,194.682527,81.454773,6.980395e-01,7.935170e-01,8.009591e-01,6.980395e-01,7.737595e-01,7.685734e-01
69,70,1.650304e+09,center1,17,"[[1650303647.5282185, 1650303647.6182182]]",[],[[]],1.650304e+09,0.093000,153.876663,114.606090,312.527191,82.663345,3.407444e-01,3.360269e-01,3.407444e-01,2.392325e-01,2.691037e-01,2.784503e-01
70,71,1.650304e+09,center1,17,"[[1650303647.6642182, 1650303647.780218]]",[],[[4]],1.650304e+09,0.118000,159.543160,145.343715,245.111464,82.204764,5.022715e-01,5.389107e-01,6.391823e-01,5.022715e-01,6.049634e-01,5.936413e-01
71,72,1.650304e+09,center1,17,"[[1650303649.7922163, 1650303649.854216], [165...",[],"[[], [0]]",1.650304e+09,0.156000,143.900853,149.473413,194.617539,81.625583,8.844058e-01,6.470263e-01,1.037334e+00,6.470263e-01,9.640063e-01,9.251901e-01
72,73,1.650304e+09,center1,17,"[[1650303652.126214, 1650303652.194214]]",[],[[]],1.650304e+09,0.082000,176.766554,172.125599,292.499531,81.048425,1.353422e+00,1.416670e+00,1.514927e+00,1.353422e+00,1.458208e+00,1.456011e+00
73,74,1.650304e+09,center1,17,"[[1650303654.2502122, 1650303654.306212], [165...","[[1650303654.308212, 1650303654.382212]]","[[], [3]]",1.650304e+09,0.177000,339.568261,291.836998,739.505018,81.987695,4.629050e-01,9.897533e-01,1.370473e+00,4.629050e-01,1.175922e+00,1.104690e+00
74,75,1.650304e+09,center1,17,"[[1650303654.4762118, 1650303654.5722115]]",[],[[4]],1.650304e+09,0.127000,226.957761,149.849132,616.220721,81.713192,7.769182e-01,6.946015e-01,7.769182e-01,3.017821e-01,4.831378e-01,4.967617e-01
75,76,1.650304e+09,center1,17,"[[1650303655.442211, 1650303655.476211]]",[],[[]],1.650304e+09,0.067000,214.847882,185.345333,418.015588,81.655766,7.575658e-02,1.357203e-01,1.357203e-01,7.575658e-02,1.105503e-01,1.095263e-01
76,77,1.650304e+09,center1,17,"[[1650303657.570209, 1650303657.592209], [1650...","[[1650303657.536209, 1650303657.568209], [1650...","[[], [], [0], [3]]",1.650304e+09,0.319001,268.276420,190.073234,807.436003,81.846117,8.667597e-01,3.516744e-01,8.667597e-01,4.909075e-02,4.400245e-01,4.317897e-01
77,78,1.650304e+09,center1,17,"[[1650303659.6062071, 1650303659.704207], [165...","[[1650303659.796207, 1650303659.8342068], [165...","[[0], [], [0], []]",1.650304e+09,0.515001,238.009180,173.912538,870.402892,82.496454,4.927598e-01,5.162809e-01,5.303883e-01,3.469569e-02,1.421916e-01,2.221597e-01
78,79,1.650304e+09,center1,17,"[[1650303660.738206, 1650303660.808206]]",[],[[]],1.650304e+09,0.072000,128.937987,115.612780,201.976704,82.018465,6.572363e-01,6.577071e-01,7.085324e-01,6.572363e-01,6.927281e-01,6.896650e-01
79,80,1.650304e+09,center1,17,"[[1650303660.834206, 1650303660.942206]]",[],[[1]],1.650304e+09,0.124001,158.071620,124.150436,375.636211,81.567037,6.343598e-01,2.847407e-01,6.343598e-01,2.265381e-01,3.716149e-01,3.966098e-01
80,81,1.650304e+09,center1,17,"[[1650303663.886203, 1650303663.990203], [1650...","[[1650303663.992203, 1650303664.022203]]","[[], []]",1.650304e+09,0.161000,168.755193,140.483949,341.030370,81.265419,9.726904e-01,1.561364e-01,9.726904e-01,1.561364e-01,5.513049e-01,5.570593e-01
81,82,1.650304e+09,center1,17,"[[1650303664.104203, 1650303664.1962028]]",[],[[2]],1.650304e+09,0.121000,153.779306,120.137831,322.468570,81.416267,1.717496e-01,7.029632e-01,7.029632e-01,1.717496e-01,3.517143e-01,3.847456e-01
82,83,1.650304e+09,center1,17,"[[1650303666.5362008, 1650303666.6082006], [16...","[[1650303666.6102006, 1650303666.6522005]]","[[], [2]]",1.650304e+09,0.275001,123.018268,121.878509,176.943667,81.562034,3.188066e+00,2.502416e+00,3.188066e+00,1.778484e+00,2.214938e+00,2.265552e+00

### 5. Decode data